#!/bin/sh
if [ $# -lt 2 ];then
  echo "Create Repository Need UserName and Repository Name"
  echo "Usage:git-create-repository "Username" "RepoName""
else
  curl -u $1 https://api.github.com/user/repos -d ''{\"name\":\"${2}\"}'' 
fi



